DROP TABLE IF EXISTS pet;
CREATE TABLE pet (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
code VARCHAR (24) NOT NULL,
type VARCHAR (50) NOT NULL,
color VARCHAR (50) NOT NULL,
country VARCHAR (50) NOT NULL
);

